# Generated by Django 3.0.4 on 2021-02-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehmgt',
            fields=[
                ('token', models.IntegerField(primary_key=True, serialize=False)),
                ('veh', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehlog',
            },
        ),
    ]
