# Generated by Django 3.0.4 on 2021-02-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehmgt',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
